<?php

namespace AppBundle\Repository;

/**
 * AutoEntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoEntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
