<?php

namespace AppBundle\Repository;

/**
 * SasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SasRepository extends \Doctrine\ORM\EntityRepository
{
}
